# Generated by Django 5.2.7 on 2025-10-26 13:47

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="studentcourse",
            options={
                "verbose_name": "Inscription étudiant",
                "verbose_name_plural": "Inscriptions étudiants",
            },
        ),
        migrations.AddField(
            model_name="course",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="course",
            name="description",
            field=models.TextField(blank=True, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="course",
            name="category",
            field=models.CharField(
                choices=[
                    ("informatique", "Informatique"),
                    ("mathematiques", "Mathématiques"),
                    ("physique", "Physique"),
                    ("chimie", "Chimie"),
                    ("biologie", "Biologie"),
                    ("commerce", "Commerce"),
                ],
                default="informatique",
                max_length=50,
                verbose_name="Catégorie",
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="instructor",
            field=models.CharField(max_length=100, verbose_name="Instructeur"),
        ),
        migrations.AlterField(
            model_name="course",
            name="name",
            field=models.CharField(max_length=200, verbose_name="Nom du cours"),
        ),
        migrations.AlterField(
            model_name="course",
            name="schedule",
            field=models.CharField(max_length=100, verbose_name="Horaire"),
        ),
        migrations.AlterField(
            model_name="studentcourse",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="courses.course",
                verbose_name="Cours",
            ),
        ),
        migrations.AlterField(
            model_name="studentcourse",
            name="enrollment_date",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Date d'inscription"
            ),
        ),
        migrations.AlterField(
            model_name="studentcourse",
            name="student_id",
            field=models.IntegerField(verbose_name="ID de l'étudiant"),
        ),
        migrations.AlterUniqueTogether(
            name="studentcourse",
            unique_together={("student_id", "course")},
        ),
    ]
